version: "3.9"
services:
  api:
    build:
      context: ./Back
      dockerfile: Dockerfile
    container_name: cms_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - MONGO__CONNECTIONSTRING=mongodb://mongo:27017
      - MONGO__DATABASE=cms_db
      - MINIO__ENDPOINT=minio:9000
      - MINIO__ACCESSKEY=minioadmin
      - MINIO__SECRETKEY=minioadmin
      - MINIO__BUCKETNAME=cms-files
    depends_on:
      - mongo
      - minio
    ports:
      - "5000:5000"
    networks:
      - cmsnet
  front:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: cms_front
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - cmsnet
  mongo:
    image: mongo:latest
    container_name: cms_mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db
    networks:
      - cmsnet
  minio:
    image: minio/minio:latest
    container_name: cms_minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - cmsnet
volumes:
  mongo_data:
  minio_data:
networks:
  cmsnet:
    driver: bridge