/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseComponenteItem: typeof import('./src/components/Base/ComponenteItem.vue')['default']
    BaseConteudoEditavel: typeof import('./src/components/Base/ConteudoEditavel.vue')['default']
    BaseEditor: typeof import('./src/components/Base/Editor.vue')['default']
    MenuComponentesCardsCard: typeof import('./src/components/Menu/Componentes/Cards/Card.vue')['default']
    MenuComponentesGenericosCabecalho: typeof import('./src/components/Menu/Componentes/Genericos/Cabecalho.vue')['default']
    MenuComponentesGenericosColuna: typeof import('./src/components/Menu/Componentes/Genericos/Coluna.vue')['default']
    MenuComponentesGenericosConfiguracaoCabecalho: typeof import('./src/components/Menu/Componentes/Genericos/Configuracao/Cabecalho.vue')['default']
    MenuComponentesGenericosConfiguracaoColuna: typeof import('./src/components/Menu/Componentes/Genericos/Configuracao/Coluna.vue')['default']
    MenuComponentesGenericosConfiguracaoLinha: typeof import('./src/components/Menu/Componentes/Genericos/Configuracao/Linha.vue')['default']
    MenuComponentesGenericosLinha: typeof import('./src/components/Menu/Componentes/Genericos/Linha.vue')['default']
    MenuComponentesParagrafosParagrafo: typeof import('./src/components/Menu/Componentes/Paragrafos/Paragrafo.vue')['default']
    MenuComponentesTitulosTitulo: typeof import('./src/components/Menu/Componentes/Titulos/Titulo.vue')['default']
    MenuConfigColuna: typeof import('./src/components/Menu/Config/Coluna.vue')['default']
    MenuConfigComponente: typeof import('./src/components/Menu/Config/Componente.vue')['default']
    MenuConfigLinha: typeof import('./src/components/Menu/Config/Linha.vue')['default']
    MenuComponente: typeof import('./src/components/Menu/Componente.vue')['default']
    MenuConfiguracao: typeof import('./src/components/Menu/Configuracao.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
