const properties = {
  // o nome estrutural é o valor!, exemplo: Nome é uma chave, e Fulano é o valor, (OOP)
  // no JSON vai registrar o VALOR... no código vai estar definido a CHAVE $cms('nome') 
  id: 'id',
  name: 'nome',
  type: 'tipo',
  attrs: 'atributos',
  container: 'filhos',
  configs: 'configuracao',
  subpages: 'subpaginas',
  meta: 'meta',
  class: 'classe',
  icon: 'icone',
  group: 'grupo',
  pageName: 'nomePagina',
  path: 'caminho',
  published: 'publicado',
  idDomain: 'dominioId',
  version: 'versao',
  endDate: 'dataFinal',
  image: 'imagem',
  desktop: 'desktop',
  mobile: 'mobile',
  imagePosition: 'posicaoImagem',
  show: 'mostrar',
  style: 'estilo',
  bgStyle: 'tipoFundo',
  content: 'conteudo',
  startsAt: 'inicial',
  endsAt: 'final',
  page: 'pagina',
  value: 'valor',
  extension: 'extensao',
  visibility: 'visibilidade',
  structure: 'estrutura',
  excludedAt: 'exclusao',
  createdAt: 'criacao',
  alteredAt: 'alteracao',
};

export default properties;